// One-time generator: parses the raw Art of War gist (data/_artofwar_raw.txt)
// into src/quotes.js. Re-run if you refresh the source.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const RAW = path.join(__dirname, '..', 'data', '_artofwar_raw.txt');
const OUT = path.join(__dirname, '..', 'src', 'quotes.js');

const text = fs.readFileSync(RAW, 'utf8');

const quotes = text
  .split('\n')
  .map((l) => l.trim())
  .filter(Boolean)
  // drop the trailing " – Sun Tzu" / "- Sun Tzu" attribution
  .map((l) => l.replace(/\s*[–\-—]\s*Sun\s*Tzu\.?\s*$/i, '').trim())
  // strip surrounding straight or curly quotes
  .map((l) => l.replace(/^[“"']+/, '').replace(/[”"']+$/, '').trim())
  .filter((l) => l.length > 0);

const body =
  '// Sun Tzu — The Art of War. Source:\n' +
  '// https://gist.github.com/DiogenesAnalytics/55c68ae7af0e58911621733e6277920e\n' +
  '// Generated by scripts/build-quotes.js — do not edit by hand.\n' +
  'export const ART_OF_WAR_QUOTES = [\n' +
  quotes.map((q) => '  ' + JSON.stringify(q) + ',').join('\n') +
  '\n];\n';

fs.writeFileSync(OUT, body);
console.log(`Wrote ${quotes.length} quotes to src/quotes.js`);
